capstonewie/CapstoneWIE/Controllers/PageController.cs
using CapstoneWIE.DataLayer.Factories;
using CapstoneWIE.DataLayer.Interfaces;
using CapstoneWIE.DataLayer.Models;
using System;
using System.Web.Mvc;

namespace CapstoneWIE.Controllers
{
    public class PageController : Controller
    {
        private readonly IPageRepository _pageRepository;

        public PageController()
        {
            _pageRepository = PageRepositoryFactory.GetRepository();
        }

        public ActionResult PageTemplate(int id)
        {
            var page = _pageRepository.Get(id);

            if (page == null)
            {
                page = new Page
                {
                    Content = "404 not found",
                    CreationDate = new DateTime(1999, 12, 31),
                    Title = "404 no title"
                };
            }

            return View(page);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult PageEdit(int id)
        {
            var page = _pageRepository.Get(id);
            return View(page);
        }
    }
}

capstonewie/CapstoneWIE/Views/Page/PageEdit.cshtml
@using Microsoft.AspNet.Identity
@model CapstoneWIE.DataLayer.Models.Page

@{
    ViewBag.Title = "PageEdit";
}


<div ng-controller="pageController">
    <div class="container" ng-init="setPage('@Model.Id')">
        <form ng-submit="editPage()" method="post">
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10">
                    <div class="form-inline" style="padding-bottom: 20px">
                        <label style="padding-top: 50px">Title:</label>
                        <input type="text" name="Title" class="form-control" ng-model="page.Title" />
                        <div style="padding-left: 35px">
                            <div class="alert-danger" style="width: 17%;" ng-show="alert.title.status" ng-bind="alert.title.message"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-1"></div>
                <div class="col-sm-10" style="width: 80%; margin-left:3%">
                    <textarea ui-tinymce="tinymceOptions" ng-model="page.Content"></textarea>
                    <div ng-show="alert.content.status" ng-bind="alert.content.message" class="alert-danger"></div>
                    <br />
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8"></div>
                <div style="text-align: right" class="col-sm-3">
                    <button type="submit" class="btn btn-sm btn-primary">Save Changes</button>
                </div>
            </div>
        </form>
    </div>
</div>

capstonewie/CapstoneWIE/Views/Page/PageTemplate.cshtml
@using System.Net.Configuration
@model CapstoneWIE.DataLayer.Models.Page

@{
    ViewBag.Title = "PageTemplate";
}

    <div class="container">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <br />
                <h1>
                    <strong>
                        @Model.Title
                    </strong>
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10" style="overflow-wrap: break-word">
                <p>
                    @Html.Raw(Model.Content)
                </p>
                <p>
                    @Model.CreationDate
                </p>
                <div ng-controller="pageController">
                    @if (User.IsInRole("Admin") && Model.ApplicationUserId != null)
                    {
                        <button class="btn btn-danger" ng-click="deletePage('@Model.Id')">Delete</button>
                        @Html.ActionLink("Edit", "PageEdit", "Page", new {id = Model.Id}, new {@class = "btn btn-primary"})
                    }
                </div>
        </div>
    </div>
</div>